name: Auto merge Dependabot PRs

on:
  pull_request_target:

jobs:
  auto-approve:
    name: Auto approve
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    needs: auto-approve
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies,javascript"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_METHOD: "rebase"
          MERGE_DELETE_BRANCH: "true"
